### PR TITLE
fix: `module-whatis` for `rcdb` should be main fork

### PR DESCRIPTION
**Pull request by c-dilks**
since the `baltzell` fork was deleted

### CODE REVIEW

**Comment by baltzell** [comment]
no, it was restored a while back (https://github.com/baltzell/rcdb/releases/tag/v1.99.6), for now ...

**Comment by c-dilks** [comment]
Why is it no longer a "GitHub" fork? Instead it's now a standalone copy.

**Comment by baltzell** [comment]
no really good reason, does that change some functionality?

**Comment by c-dilks** [comment]
It just makes it harder to "discover" your fork, which is why I thought it was deleted. You can still configure your remotes to sync the forks etc.

**Pull request closed without merging**
